steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/todo-repo/todo-app',
      '.'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [
      'gcloud', 'run', 'deploy', 'todo-app',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/todo-repo/todo-app',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--project', '$PROJECT_ID'
    ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/todo-repo/todo-app'

options:
  logging: CLOUD_LOGGING_ONLY